# Generated from Carapace
# Todo: Validate it against documentation
# Todo: Add Static and Dynamic Sources where appropriate
[PowerTypeDictionary]@{
    Platforms   = ([Platforms]::All);
    State       = [DictionaryState]::Generated -bor [DictionaryState]::Experimental -bor [DictionaryState]::Incomplete;
    Source      = "Carapace";
    Url         = "https://ant.apache.org/";
    Keys        = @("ant");
    Name        = "ant";
    Description = "software tool for automating software build processes";
    Parameters  = @(
        [FlagParameter]@{
            Keys        = @("---execdebug");
            Name        = "print ant exec line generated by this launch script";
            Description = "print ant exec line generated by this launch script";
        },
        [FlagParameter]@{
            Keys        = @("---h");
            Name        = "print this message and ant help";
            Description = "print this message and ant help";
        },
        [FlagParameter]@{
            Keys        = @("---help");
            Name        = "print this message and ant help";
            Description = "print this message and ant help";
        },
        [FlagParameter]@{
            Keys        = @("---noconfig");
            Name        = "suppress sourcing of configuration files";
            Description = "suppress sourcing of configuration files";
        },
        [FlagParameter]@{
            Keys        = @("---usejikes");
            Name        = "enable use of jikes by default, unless set explicitly in configuration files";
            Description = "enable use of jikes by default, unless set explicitly in configuration files";
        },
        [FlagParameter]@{
            Keys        = @("--autoproxy");
            Name        = "Java1.5+: use the OS proxy settings";
            Description = "Java1.5+: use the OS proxy settings";
        },
        [ValueParameter]@{
            Keys        = @("--buildfile");
            Name        = "use given buildfile";
            Description = "use given buildfile";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--debug");
            Name        = "print debugging information";
            Description = "print debugging information";
        },
        [FlagParameter]@{
            Keys        = @("--diagnostics");
            Name        = "print information that might be helpful to";
            Description = "print information that might be helpful to";
        },
        [FlagParameter]@{
            Keys        = @("--emacs");
            Name        = "produce logging information without adornments";
            Description = "produce logging information without adornments";
        },
        [ValueParameter]@{
            Keys        = @("--f");
            Name        = "use given buildfile";
            Description = "use given buildfile";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--file");
            Name        = "use given buildfile";
            Description = "use given buildfile";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--find");
            Name        = "(s)earch for buildfile towards the root of";
            Description = "(s)earch for buildfile towards the root of";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--help");
            Name        = "print this message and exit";
            Description = "print this message and exit";
        },
        [ValueParameter]@{
            Keys        = @("--inputhandler");
            Name        = "the class which will handle input requests";
            Description = "the class which will handle input requests";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--k");
            Name        = "execute all targets that do not depend on failed target(s)";
            Description = "execute all targets that do not depend on failed target(s)";
        },
        [FlagParameter]@{
            Keys        = @("--keep-going");
            Name        = "execute all targets that do not depend on failed target(s)";
            Description = "execute all targets that do not depend on failed target(s)";
        },
        [ValueParameter]@{
            Keys        = @("--l");
            Name        = "use given file for log";
            Description = "use given file for log";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--lib");
            Name        = "specifies a path to search for jars and classes";
            Description = "specifies a path to search for jars and classes";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--listener");
            Name        = "add an instance of class as a project listener";
            Description = "add an instance of class as a project listener";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--logfile");
            Name        = "use given file for log";
            Description = "use given file for log";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--logger");
            Name        = "the class which is to perform logging";
            Description = "the class which is to perform logging";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--main");
            Name        = "override Ant's normal entry point";
            Description = "override Ant's normal entry point";
            # Source = $?? # todo: Fix or remove this!
        },
        [ValueParameter]@{
            Keys        = @("--nice");
            Name        = "A niceness value for the main thread";
            Description = "A niceness value for the main thread";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--noclasspath");
            Name        = "Run ant without using CLASSPATH";
            Description = "Run ant without using CLASSPATH";
        },
        [FlagParameter]@{
            Keys        = @("--noinput");
            Name        = "do not allow interactive input";
            Description = "do not allow interactive input";
        },
        [FlagParameter]@{
            Keys        = @("--nouserlib");
            Name        = "Run ant without using the jar files from `${user.home}/.ant/lib";
            Description = "Run ant without using the jar files from `${user.home}/.ant/lib";
        },
        [FlagParameter]@{
            Keys        = @("--projecthelp");
            Name        = "print project help information and exit";
            Description = "print project help information and exit";
        },
        [ValueParameter]@{
            Keys        = @("--propertyfile");
            Name        = "load all properties from file with -D properties taking precedence";
            Description = "load all properties from file with -D properties taking precedence";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--quiet");
            Name        = "be extra quiet";
            Description = "be extra quiet";
        },
        [ValueParameter]@{
            Keys        = @("--s");
            Name        = "(s)earch for buildfile towards the root of";
            Description = "(s)earch for buildfile towards the root of";
            # Source = $?? # todo: Fix or remove this!
        },
        [FlagParameter]@{
            Keys        = @("--silent");
            Name        = "print nothing but task outputs and build failures";
            Description = "print nothing but task outputs and build failures";
        },
        [FlagParameter]@{
            Keys        = @("--verbose");
            Name        = "be extra verbose";
            Description = "be extra verbose";
        },
        [FlagParameter]@{
            Keys        = @("--version");
            Name        = "print the version information and exit";
            Description = "print the version information and exit";
        }
    )
}
