name: create git dictionary base

on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'git cli repository tag'     
        required: true
        default: 'v2.34.1'     

jobs:
  create-base:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout local
      uses: actions/checkout@v2
      with:
        path: 'PowerType'
      
    - name: Checkout github
      uses: actions/checkout@v2
      with:
        repository: 'git/git'
        ref: 'refs/tags/${{ github.event.inputs.gitTag }}'
        path: 'git'

    - name: Install dependencies
      run: sudo apt-get install -y build-essential asciidoc

    - name: Create documentation
      run: |
        echo $PWD
        cd git/Documentation
        make
        echo $PWD
    
    - name: Move xml documentation
      run: |
        echo $PWD
        mv -v git/Documentation/*.xml PowerType/GenerateDictionaries/git/
      
    - name: Transform asciidoc to powershell
      shell: pwsh
      run: |
        Write-Host $pwd
        cd 'PowerType/GenerateDictionaries/git'
        Write-Host $pwd
        ./asciidoc.to.dictionary.ps1

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: git dictionary base
        path: 'PowerType/generate dictionaries/git/output.ps1'
