name: Publish

on:
  release:
    types: [created]

jobs:
  pack:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: dotnet restore --verbosity normal --locked-mode
    
    - name: Build
      run: dotnet build --configuration Release --no-restore /property:Version=${{ github.event.release.tag_name }}

    - name: Change PowerShell module version and release notes
      shell: pwsh
      run: |
        $file = 'artifacts\PowerType\PowerType.psd1'
        Update-ModuleManifest $file -ModuleVersion '${{ github.event.release.tag_name }}' -ReleaseNotes '${{ github.event.release.body }}'

    - name: Enable Prerelease
      if: github.event.release.prerelease == true
      shell: pwsh
      run: |
        $file = 'artifacts\PowerType\PowerType.psd1'
        Update-ModuleManifest $file -Prerelease 'preview'

    - name: Publish and upload artifacts
      shell: pwsh
      run: |
        Publish-Module -Path 'artifacts\PowerType' -NuGetApiKey '${{ secrets.POWERSHELL_GALLERY_API_KEY }}'
