name: unit tests

on: [push, pull_request]

jobs:
  Unit-Test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      continue-on-error: true
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov

    - name: Find lcov file path
      id: find-lcov-file-path
      shell: pwsh
      run: |
        $FilePath = (Get-ChildItem PowerType.Tests\TestResults\* | Select-Object -First 1 | Get-ChildItem).FullName
        Write-Host ::set-output name=path::$FilePath

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ steps.find-lcov-file-path.outputs.path }}
